name: "Annotate ESLint from the JSON report"
description: "Pull request diffs are annotated with error and warnings from an ESLint report JSON file."
inputs:
  eslint-report-json:
    description: "ESLint report file in JSON format."
    default: "eslint_report.json"
    required: false
runs:
  using: "node16"
  main: "build/index.js"
branding:
  icon: "check-circle"
  color: "yellow"
